import { DocumentData } from '../types';

/**
 * Generate a standalone Python inspection & validation script for the golden data JSON.
 */
export function generatePythonScript(data: DocumentData, filename = 'outline_tree.json'): string {
  return `#!/usr/bin/env python3
"""
Document Outline Golden Data Inspector & Local Server
Auto-generated by Document Outline Annotator
"""

import json
import sys
import os
from typing import Dict, Any, List

DATA_FILE = "${filename}"

def print_tree(node: Dict[str, Any], prefix: str = "", is_last: bool = True):
    depth = node.get("depth", 0)
    label = f"[{node.get('label')}] " if node.get('label') else ""
    title = node.get("title", "(No Title)")
    node_id = node.get("id", "")
    text_preview = node.get("text", "").replace("\\n", " ")[:40]
    if text_preview:
        text_preview = f" -> \\"{text_preview}...\\""
        
    marker = "└── " if is_last else "├── "
    branch = prefix + marker if depth > 0 else ""
    print(f"{branch}{label}{title} (id: {node_id}, depth: {depth}){text_preview}")
    
    children: List[Dict[str, Any]] = node.get("children", [])
    new_prefix = prefix + ("    " if is_last else "│   ") if depth > 0 else ""
    
    for i, child in enumerate(children):
        is_child_last = (i == len(children) - 1)
        print_tree(child, new_prefix, is_child_last)

def validate(node: Dict[str, Any], expected_depth: int = 0) -> List[str]:
    errors = []
    actual_depth = node.get("depth")
    if actual_depth != expected_depth:
        errors.append(f"Depth mismatch at {node.get('id')}: expected {expected_depth}, got {actual_depth}")
        
    for child in node.get("children", []):
        errors.extend(validate(child, expected_depth + 1))
    return errors

def main():
    target = DATA_FILE if len(sys.argv) < 2 else sys.argv[1]
    
    if not os.path.exists(target):
        print(f"Error: File '{target}' not found!")
        print(f"Usage: python3 {os.path.basename(__file__)} [path_to_json]")
        sys.exit(1)
        
    with open(target, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    root = data.get("root")
    if not root:
        print("Invalid format: 'root' key not found.")
        sys.exit(1)
        
    print("=" * 60)
    print("DOCUMENT OUTLINE TREE (Golden Data)")
    print("=" * 60)
    print_tree(root)
    print("=" * 60)
    
    errors = validate(root, 0)
    if errors:
        print("Validation Warnings:")
        for e in errors:
            print("  [FAIL]", e)
    else:
        print("✓ All node depths and hierarchies verified successfully!")

if __name__ == "__main__":
    main()
`;
}

/**
 * Generate a standalone Python HTTP server script with interactive API to save directly to disk
 */
export function generatePythonApiServer(jsonFilename = 'outline_tree.json'): string {
  return `#!/usr/bin/env python3
"""
Simple Python local save-server for Document Outline Annotator
Runs a lightweight HTTP server on port 8000 that allows saving outline_tree.json directly to disk.
"""

import json
import os
from http.server import HTTPServer, SimpleHTTPRequestHandler

PORT = 8000
DATA_FILE = "${jsonFilename}"

class AnnotatorHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        # Enable CORS for local app interaction
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.end_headers()

    def do_GET(self):
        if self.path == '/api/load':
            if os.path.exists(DATA_FILE):
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                with open(DATA_FILE, 'rb') as f:
                    self.wfile.write(f.read())
            else:
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b'{"error": "File not found"}')
        else:
            super().do_GET()

    def do_POST(self):
        if self.path == '/api/save':
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length)
            try:
                data = json.loads(post_data)
                with open(DATA_FILE, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=2, ensure_ascii=False)
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(b'{"status": "saved", "file": "' + DATA_FILE.encode('utf-8') + b'"}')
                print(f"[✓] Saved updated outline to {DATA_FILE}")
            except Exception as e:
                self.send_response(500)
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

print(f"Starting Document Outline local server on http://localhost:{PORT}")
print(f"Serving data file: {os.path.abspath(DATA_FILE)}")
server = HTTPServer(('localhost', PORT), AnnotatorHandler)
try:
    server.serve_forever()
except KeyboardInterrupt:
    print("\\nServer stopped.")
`;
}
